version: '3'
name: 10cordes
volumes:
  postgres-data:
networks:
  backend:

services:
  db:
    image: 'postgres:15'
    container_name: cordes-db
    restart: always
    ports:
      - 5456:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cordes
    networks:
      - backend
    volumes:
      - ./database/pgdatacordes:/var/lib/postgresql/data
