name: dixcordes
volumes:
  postgres-data:
  cassandra-data:
  redis-data:
networks:
  backend:

services:
  db:
    image: 'postgres:15'
    container_name: cordes-db
    restart: always
    ports:
      - 5456:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cordes
    networks:
      - backend
    volumes:
      - ./database/pgdatacordes:/var/lib/postgresql/data
  cassandra:
    image: 'cassandra:4.1.5'
    container_name: cordes-cassandra
    restart: always
    environment:
      - CASSANDRA_KEYSPACE=dixcordes
      - CASSANDRA_USER=cordes
      - CASSANDRA_PASSWORD=cordes
    ports:
      - 9042:9042
    networks:
      - backend
    volumes:
      - ./database/cassandradata:/var/lib/cassandra
  redis:
    image: 'redis:7.2.5-alpine'
    container_name: cordes-redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - backend
    volumes:
      - ./database/redis-data:/data
